# Generated by Django 3.0.5 on 2020-04-29 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_auto_20200429_0841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='candidate',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
