# Generated by Django 3.0.5 on 2020-04-29 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_auto_20200429_0842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='candidate',
            field=models.CharField(default='', max_length=255),
        ),
    ]
